Especialista/urls.py
# coding=utf-8
from django.conf.urls import patterns, include, url
from django.views.generic import DetailView, ListView, CreateView
from django.contrib.auth.decorators import login_required
from Personas.models import DatosDePacienteAdulto, DatosDePacienteAdolescente

urlpatterns = patterns('',
    url(r'^Paciente/Adulto/(?P<pk>\d+)/CrearFicha/(?P<tipo>social|psicologica|medica|juridica)/$', 'Especialista.views.CrearFicha', name='crearFicha'),
    url(r'^Paciente/Adulto/(?P<pk>\d+)/ModificarFicha/(?P<tipo>social|psicologica|medica|juridica)/(?P<ficha_pk>\d+)/$', 'Especialista.views.CrearFicha', name='modificar_ficha'),
    url(r'^Paciente/Adulto/(?P<pk>\d+)/VerFicha/(?P<tipo>social|psicologica|medica|juridica)/(?P<ficha_pk>\d+)/$', 'Especialista.views.VerFicha', name="ver_ficha"),
    url(r'^Paciente/Adulto/(?P<pk>\d+)/Ficha/(?P<tipo>social|psicologica|medica|juridica)/$', 'Especialista.views.FichaListado', name='ficha_adulto_listado'),
    url(r'^Paciente/Infante/(?P<pk>\d+)/Ficha/$', 'Especialista.views.FichaListadoInfante', name='ficha_infante_listado'),
    url(r'^Paciente/Infante/(?P<pk>\d+)/CrearFicha/$', 'Especialista.views.CrearFichaInfante', name='crear_ficha_infante'),
    url(r'^Paciente/Infante/(?P<pk>\d+)/VerFicha/(?P<tipo>psicosocial)/(?P<ficha_pk>\d+)/$', 'Especialista.views.VerFicha', name = 'ver_ficha_infante'),
    url(r'^Paciente/Infante/(?P<pk>\d+)/ModificarFicha/(?P<ficha_pk>\d+)/$', 'Especialista.views.CrearFichaInfante', name = 'modificar_ficha_infante'),
    url(r'^Paciente/Adolescente/(?P<pk>\d+)/Ficha/(?P<tipo>social|psicologica)/$', 'Especialista.views.FichaListadoAdolescente', name='ficha_adolescente_listado'),
    url(r'^Paciente/Adolescente/(?P<pk>\d+)/CrearFicha/(?P<tipo>social|psicologica)/$', 'Especialista.views.CrearFichaAdolescente', name='crear_ficha_adolescente'),
    url(r'^Paciente/Adolescente/(?P<pk>\d+)/VerFicha/(?P<tipo>social|psicologica)/(?P<ficha_pk>\d+)/$', 'Especialista.views.VerFicha', name='ver_ficha_adolescente'),
    url(r'^Paciente/Adolescente/(?P<pk>\d+)/ModificarFicha/(?P<tipo>social|psicologica)/(?P<ficha_pk>\d+)/$', 'Especialista.views.CrearFichaAdolescente', name = 'modificar_ficha_adolescente'),
    url(r'^Paciente/Adulto/(?P<pk>\d+)/Imprimir/(?P<tipo>social|psicologica|medica|juridica)/(?P<ficha_pk>\d+)/$', 'Especialista.views.ImprimirFicha', name="imprimir_ficha"),
    url(r'^Paciente/Infante/(?P<pk>\d+)/Imprimir/(?P<tipo>psicosocial)/(?P<ficha_pk>\d+)/$', 'Especialista.views.ImprimirFicha', name = 'imprimir_ficha'),
    )

KunaAty/urls.py
# coding=utf-8
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', "KunaAty.views.inicio"),
    url(r'^Informes/', include('Informes.urls')),
    url(r'^Administracion/', include('Administracion.urls')),
    url(r'^Especialista/', include('Especialista.urls')),
    url(r'^Usuarios/', include('Usuarios.urls')),
    url(r'^Recepcionista/', include('Recepcionista.urls')),
    url(r'^Personas/', include('Personas.urls')),
)

pisa-3.0.33/pisa-3.0.33/demo/djangoproject/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
    (r'^$', 'djangoproject.views.index'),
    (r'^download', 'djangoproject.views.download'),
    (r'^ezpdf_sample', 'djangoproject.views.ezpdf_sample'),
    
)

Especialista/models.py
# coding=utf-8
from django.db import models
from django.core.urlresolvers import reverse
from Personas.models import DatosAdultos, DatosPersonalesBasicos, Direccion, DatosAgresor, DatosLaborales, DatosLaboralesAdolescentes 
from Usuarios.models import KunaAtyUsuario
import datetime

class RelacionConAgresor:
    Opciones = ((0, "Esposo"),
                (1, "Concubino"),
                (2, "Novio"),
                (3, "Ex esposo"),
                (4, "Ex concubino"),
                (5, "Ex novio"),
                (6, "Padre"),
                (7, "Hijo/a"),
                (8, "Otro"))

class Oinstitucion:
    Opciones = ((1, "Juzgado"), (2, "Comisaría"), (3, "Hospital"), (4, "Centro de Salud"))
    
class Llegada:
    Opciones = ((0, "Radio"),
                (1, "Televisión"),
                (2, "Internet"),
                (3, "Periódico"),
                (4, "Otra usuaria"),
                (5, "Otra institución"), ## como agregar una subopción de otra institución?
                (6, "Amigos/as"),
                (7, "Familiares"))


################################### Otras clases ############################################
class MotivoDeConsulta(models.Model):
    nombre = models.CharField(max_length = 35)
    
    def __unicode__(self):
        return self.nombre

class TiposDeViolencia(models.Model):
    nombre = models.CharField(max_length = 25)
    
    def __unicode__(self):
        return self.nombre


class ViolenciaFrecuencia(models.Model):
    nombre = models.CharField(max_length = 25)
    predeterminado = models.BooleanField(default = False)
    
    def __unicode__(self):
        return self.nombre

################################### Ficha Base ##############################################
class FichaBase(models.Model):
    Paciente = models.ForeignKey(DatosPersonalesBasicos, null = True, blank = True)
    FechaActualizada = models.DateField(default = datetime.date.today, verbose_name = "Fecha Actualizada")
    ProfesionalTratante=models.ForeignKey(KunaAtyUsuario, verbose_name = "Profesional Tratante")
    Finalizado=models.BooleanField(verbose_name = "Es un caso Finalizado?")
    @property
    def ficha_type(self):
        return {"ad_social": "social",
                "ad_psicologica": "psicologica"}.get(self._ficha_tipo_interno, self._ficha_tipo_interno)
    
    @property
    def _ficha_tipo_interno(self):
        if not hasattr(self, "_tipo_guardado"):
            self._tipo_guardado = self._ficha_type_interior()
        return self._tipo_guardado

    def _ficha_type_interior(self):
        try:
            if self.fichasocial is not None:
                return "social"
        except FichaSocial.DoesNotExist:
            pass
        try:
            if self.fichamedica:
                return "medica"
        except FichaMedica.DoesNotExist:
            pass
        try:
            if self.fichajuridica:
                return "juridica"
        except FichaJuridica.DoesNotExist:
            pass
        try:
            if self.fichapsicologica:
                return "psicologica"
        except FichaPsicologica.DoesNotExist:
            pass
        try:
            if self.fichapsicologicaadolescente:
                return "ad_psicologica"
        except FichaPsicologicaAdolescente.DoesNotExist:
            pass
        try:
            if self.fichasocialadolescente:
                return "ad_social"
        except FichaSocialAdolescente.DoesNotExist:
            pass
        try:
            if self.fichainfantil:
                return "infantil"
        except FichaInfantil.DoesNotExist:
            pass
        return ""
    
    @classmethod
    def get_model(cls, tipo):
        return {"social": FichaSocial,
                "medica": FichaMedica,
                "juridica": FichaJuridica,
                "psicologica": FichaPsicologica,
                "ad_social": FichaSocialAdolescente,
                "ad_psicologica": FichaPsicologicaAdolescente,
                "infantil": FichaInfantil
                }.get(tipo, None)
    
    @property
    def model(self):
        return FichaBase.get_model(self._ficha_tipo_interno)

    @property
    def sub_model(self):
        if self._ficha_tipo_interno == "social":
            return self.fichasocial
        if self._ficha_tipo_interno == "medica":
            return self.fichamedica
        if self._ficha_tipo_interno == "juridica":
            return self.fichajuridica
        if self._ficha_tipo_interno == "psicologica":
            return self.fichapsicologica
        if self._ficha_tipo_interno == "ad_psicologica":
            return self.fichapsicologicaadolescente
        if self._ficha_tipo_interno == "ad_social":
            return self.fichasocialadolescente
        if self._ficha_tipo_interno == "infantil":
            return self.fichainfantil
        return None

    def get_absolute_url(self):
        return self.sub_model.get_absolute_url()
    
    def get_modificar_enlace(self):
        return reverse("modificar_ficha", kwargs = {"pk": self.Paciente.pk, "tipo": self.ficha_type, "ficha_pk": self.pk})

class Observacion(models.Model):
    texto = models.TextField()
    fecha = models.DateField(default = datetime.date.today)
    ficha = models.ForeignKey(FichaBase)
################################### Fichas Infantiles #######################################
class FuenteDeDerivacion(models.Model):
    Institucion = models.CharField(max_length = 30, verbose_name = "Institución")
    Direccion = models.OneToOneField(Direccion, related_name = "+", verbose_name = "Dirección")
    Telefono = models.CharField(max_length = 15, verbose_name = "Teléfono")

class IntervencionAnterior(models.Model):
    Institucion = models.CharField(max_length = 30, verbose_name = "Institución")
    MotivoDeConsulta = models.CharField(max_length = 40, verbose_name = "Motivo de Consulta")
    Resultado = models.CharField(max_length = 50, verbose_name = "Resultado de la Intervención")

class IndicadoresFisicosInfantiles(models.Model):
    nombre = models.CharField(max_length = 30)
    predeterminado = models.BooleanField()
    
    def __unicode__(self):
        return self.nombre

class IndicadoresEmocionalesInfantiles(models.Model):
    nombre = models.CharField(max_length = 30)
    predeterminado = models.BooleanField()
    
    def __unicode__(self):
        return self.nombre

class IndicadoresCognitivosInfantiles(models.Model):
    nombre = models.CharField(max_length = 30)
    predeterminado = models.BooleanField()
    
    def __unicode__(self):
        return self.nombre

class IndicadoresComportamentalesInfantiles(models.Model):
    nombre = models.CharField(max_length = 30)
    predeterminado = models.BooleanField()
    
    def __unicode__(self):
        return self.nombre

class FichaInfantil(FichaBase):
    FuenteDerivacion = models.OneToOneField(FuenteDeDerivacion, verbose_name = "Fuente de Derivación", null = True, blank = True)
    Intervenciones = models.OneToOneField(IntervencionAnterior, verbose_name = "Intervenciones", null = True, blank = True)
    MotivosDeConsulta = models.ManyToManyField(MotivoDeConsulta, verbose_name = "Motivos de Consulta", related_name = "fsi+", null = True, blank = True)
    TipoDeViolencia = models.ManyToManyField(TiposDeViolencia, verbose_name = "Tipo de Violencia", related_name = "fsi+", null = True, blank = True)
    IndicadoresFisicos = models.ManyToManyField(IndicadoresFisicosInfantiles, verbose_name = "Indicadores Físicos", related_name = "+", blank = True)
    IndicadoresEmocionales = models.ManyToManyField(IndicadoresEmocionalesInfantiles, verbose_name = "Indicadores Emocionales", related_name = "+", blank = True)
    IndicadoresCognitivos = models.ManyToManyField(IndicadoresCognitivosInfantiles, verbose_name = "Indicadores Cognitivos", related_name = "+", blank = True)
    IndicadoresComportamentales = models.ManyToManyField(IndicadoresComportamentalesInfantiles, verbose_name = "Indicadores Comportamentales", related_name = "+", blank = True)
    HistoriaFamiliar = models.TextField(verbose_name = "Historia Familiar", null  = True, blank = True)
    Seguimientos = models.TextField(null = True, blank = True)
    
    def get_absolute_url(self):
        return reverse('ver_ficha_infante', kwargs = {"pk": self.Paciente.pk, "tipo": "psicosocial", "ficha_pk": self.pk})
    
    def get_modificar_enlace(self):
        return reverse('modificar_ficha_infante', kwargs = {"pk": self.Paciente.pk, "ficha_pk": self.pk})
    
################################### Fichas Adolescentes #####################################
class FichaSocialAdolescente(FichaBase):
    Agresor = models.OneToOneField(DatosAgresor, null = True, blank = True, related_name = "PacienteAdolescente")
    ViveConAgresor=models.BooleanField(verbose_name = "¿Vive con agresor?")
    RelacionConAgresor=models.IntegerField(choices = RelacionConAgresor.Opciones, verbose_name = "Relación con el Agresor")
    MotivosDeConsulta = models.ManyToManyField(MotivoDeConsulta, related_name = "fsa+", verbose_name = "Motivos de Consulta")
    TipoDeViolencia = models.ManyToManyField(TiposDeViolencia, related_name = "fsa+", verbose_name = "Tipo de Violencia")
    FrecuenciaDeViolencia = models.ForeignKey(ViolenciaFrecuencia, related_name = "fsa+", verbose_name = "Frecuencia de Violencia")
    DiagnosticoMedico = models.BooleanField(verbose_name = "¿Realizó diagnóstico médico?")
    DenunciaComisaria= models.BooleanField(verbose_name = "¿Realizó denuncia en la comisaría?")
    DenunciaJuridico= models.BooleanField(verbose_name = "¿Realizó denuncia jurídica?")
    DenunciaPolicia= models.BooleanField(verbose_name = "¿Realizó denuncia con la policía?")
    DenunciaFiscalia= models.BooleanField(verbose_name = "¿Realizó denuncia en la fiscalía?")
    ComoSabiaDeKunaAty = models.IntegerField(choices = Llegada.Opciones, verbose_name = "¿Cómo sabía de Kuña Aty?")

    def get_fields(self):

Especialista/templates/ficha.html
{% extends "columna_pagina.html" %}
{% load static %}
{% block cabecera %}
{{ block.super }}
{{ ficha.media }}
{% endblock %}
{% block columnaIzq %}
{% include "partes/persona_menu.html" with object=paciente %}	
{% endblock %}
{% block columnaDer %}
<script type="text/javascript">

jQuery(function($){
	$.datepicker.regional['es'] = {
		closeText: 'Cerrar',
		prevText: '&#x3c;Ant',
		nextText: 'Sig&#x3e;',
		currentText: 'Hoy',
		monthNames: ['Enero','Febrero','Marzo','Abril','Mayo','Junio',
		'Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
		monthNamesShort: ['Ene','Feb','Mar','Abr','May','Jun',
		'Jul','Ago','Sep','Oct','Nov','Dic'],
		dayNames: ['Domingo','Lunes','Martes','Mi&eacute;rcoles','Jueves','Viernes','S&aacute;bado'],
		dayNamesShort: ['Dom','Lun','Mar','Mi&eacute;','Juv','Vie','S&aacute;b'],
		dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','S&aacute;'],
		weekHeader: 'Sm',
		dateFormat: 'dd/mm/yy',
		firstDay: 1,
		isRTL: false,
		showMonthAfterYear: false,
		yearSuffix: ''};
	$.datepicker.setDefaults($.datepicker.regional['es']);
});    

        $(document).ready(function() {
           $(".datepicker").datepicker({
			yearRange: "-100:+0",
			changeYear: true,
			changeMonth: true
		   });
        });
    </script>
<div class="formficha" id="stylesFi">
<h1>Ficha</h1>
<form id="finalizado" method ="post" action=".">
	<table>
		{{ ficha.as_table }}
	</table>
	{% for f in extras %}
		{% if f.titulo %}
			<h3>{{ f.titulo }}</h3>
		{% endif %}
		<table>
			{{ f }}
		</table>
	{% endfor %}
	<h4>Observaciones</h4>
{{ obs.management_form }}
{{ obs.non_form_errors }}
<table id="formset" class="form">
{% for form in obs %}
  {% if forloop.first %}
  <thead><tr>
    {% for field in form.visible_fields %}
    <th>{{ field.label|capfirst }}</th>
   
   {% endfor %}
  </tr></thead>
  {% endif %}
  <tr class="{% cycle row1,row2 %}">
  {% for field in form.visible_fields %}
    <td>
    {# Include the hidden fields in the form #}
    {% if forloop.first %}
      {% for hidden in form.hidden_fields %}
      {{ hidden }}
      {% endfor %}
    {% endif %}
      {{ field.errors.as_ul }}
      {{ field }}
    </td>
  {% endfor %}
  </tr>
{% endfor %}
</table>
	{% csrf_token %}
	<input type="submit" class="button" value="Guardar" />
</form>
</div>
{%comment%}{%if "ficha-Finalizado" %}
<script>
	$("#finalizado").validate({
		rules: {"ficha-Fecha_Inicio": {
				required: true
			},
			"ficha-Fecha_Resolucion": {
				required: true
			},
			"ficha-Nro_Resolucion": {
				required: true
			},
			"ficha-Juzgado": {
				required: true
			},
			"ficha-Secretaria": {
				required: true
			},
			"ficha-Caratula_Expediente": {
				required: true
			}
			},
		messages: {
			"ficha-Fecha_Inicio": {
				required: "La Fecha de Inicio es requirida para finalizar este caso"
			},
			"ficha-Fecha_Resolucion": {
				required: "La Fecha de Resolución es requirida para finalizar este caso"
			},
			"ficha-Nro_Resolucion": {
				required: "El Nro. de Resolución es requirido para finalizar este caso"
			},
			"ficha-Juzgado": {
				required: "Indique el Juzgado para finalizar este caso"
			},
			"ficha-Secretaria": {
				required: "Este dato es necesario para finalizar este caso"
			},
			"ficha-Caratula_Expediente": {
				required: "Indique la Carátula para finalizar este caso"
			}
		}
	});
	</script>
{%endif%}
{%endcomment%}
{% endblock %}

Especialista/templates/ficha_adolescente_listado.html
{% extends "columna_pagina.html" %}
{% load static %}
{% block columnaIzq %}
	{% include "partes/persona_menu.html" with object=paciente %}
{% endblock %}
{% block columnaDer %}
<div class="data">
	<h3>Ficha {{ tipo|capfirst }}</h3>
	<div class="datagrid">
	<ul>
		{% for ficha in fichas %}
			<li><a href="{{ ficha.get_absolute_url }}">{{ ficha.FechaActualizada }}</a></li>
		{% endfor %}
        {% if user.Especialidad = 3 and tipo == 'psicologica'%}
		<li><a href="{% url 'crear_ficha_adolescente' pk=paciente.pk tipo=tipo %}">Crear Consulta Nueva</a></li>
        {%endif%}
        
        {% if user.Especialidad = 1 and tipo == 'social'%}
		<li><a href="{% url 'crear_ficha_adolescente' pk=paciente.pk tipo=tipo %}">Crear Consulta Nueva</a></li>
        {%endif%}
	</ul>
</div>
<div class="datagrid">
    <h1>Historial Fichas del Paciente</h1>
	
	<table>
		<thead>
		<th align="center">Ficha {{ tipo|capfirst }}</th></tr>
		</thead>
		<tbody>
		<tr>
			<td align="center">
            {% for ficha in fichasFinalizado %}
            <li><a href="{{ ficha.get_absolute_url }}">{{ ficha.FechaActualizada }}</a></li>
            {% endfor %}
            </td>
        </tr>
        </table>
	</div>
{% endblock %}

Especialista/templates/ficha_infante_listado.html
{% extends "columna_pagina.html" %}
{% load static %}
{% block columnaIzq %}
	{% include "partes/persona_menu.html" with object=paciente %}
{% endblock %}
{% block columnaDer %}
<div class="data">
	<h3>Ficha {{ tipo|capfirst }}</h3>
	<div class="datagrid">
	<ul>
		{% for ficha in fichas %}
			<li><a href="{{ ficha.get_absolute_url }}">{{ ficha.FechaActualizada }}</a></li>
		{% endfor %}
        {% if user.Especialidad = 3 %}
		<li><a href="{% url 'crear_ficha_infante' pk=paciente.pk %}">Crear Consulta Nueva</a></li>
        {%endif%}
	</ul>
	</div>
     
	<div class="datagrid">
	<h1>Fichas Inactivas del Paciente</h1>
	<table>
		<thead>
		<th align="center"> Ficha {{ tipo|capfirst }}</th></tr>
		</thead>
		<tbody>
		<tr>
			<td align="center">
            {% for ficha in fichasFinalizado %}
            <li><a href="{{ ficha.get_absolute_url }}">{{ ficha.FechaActualizada }}</a></li>
            {% endfor %}
            </td>
         </tr>
         </table>
     </div>
		 
{% endblock %}

Especialista/templates/ficha_listado.html
{% extends "columna_pagina.html" %}
{% load static %}
{% block columnaIzq %}
	{% include "partes/persona_menu.html" with object=paciente %}
{% endblock %}
{% block columnaDer %}
<div class="data">
	<h1>Ficha {{ tipo|capfirst }}</h1>
	<div class="datagrid">
	<ul>
    
		{% for ficha in fichas %}
		<li><a href="{{ ficha.get_absolute_url }}">{{ ficha.FechaActualizada }}</a></li>	
		{% endfor %}
        {% if user.Especialidad = 3 and tipo == 'psicologica'%}
		<li><a href="{% url 'crearFicha' pk=paciente.pk tipo=tipo %}">Crear Consulta Nueva</a></li>
        {%endif%}
        
        {% if user.Especialidad = 2 and tipo == 'juridica'%}
		<li><a href="{% url 'crearFicha' pk=paciente.pk tipo=tipo %}">Crear Consulta Nueva</a></li>
        {%endif%}
        
        {% if user.Especialidad = 4 and tipo == 'medica'%}
		<li><a href="{% url 'crearFicha' pk=paciente.pk tipo=tipo %}">Crear Consulta Nueva</a></li>
        {%endif%}
        
        {% if user.Especialidad = 1 and tipo == 'social'%}
		<li><a href="{% url 'crearFicha' pk=paciente.pk tipo=tipo %}">Crear Consulta Nueva</a></li>
        {%endif%}
        
	</ul>
	</div>
	<div class="datagrid">
    <h1>Historial Fichas del Paciente</h1>
	
	<table>
		<thead>
		<th align="center">Ficha {{ tipo|capfirst }}</th></tr>
		</thead>
		<tbody>
		<tr>
			<td align="center">
            {% for ficha in fichasFinalizado %}
            <li><a href="{{ ficha.get_absolute_url }}">{{ ficha.FechaActualizada }}</a></li>
            {% endfor %}
            </td>
          		</tr>
	</table>
	</div>
{% endblock %}

Especialista/templates/paciente_form.html
{% extends "base.html" %}
{% load static %}
{% block cabecera %}
{{ block.super }}
{{ form.media }}
{% endblock %}
{% block contenido %}
<form method="POST" action="{% url 'agregar_paciente' %}">
<table>
	{{ form.as_table }}
</table>
<h2>Hijos</h2>
{{ hijos.management_form }}
{{ hijos.non_form_errors }}
<table id="formset" class="form">
{% for form in hijos %}
  {% if forloop.first %}
  <thead><tr>
    {% for field in form.visible_fields %}
    <th>{{ field.label|capfirst }}</th>
    {% endfor %}
  </tr></thead>
  {% endif %}
  <tr class="{% cycle row1,row2 %}">
  {% for field in form.visible_fields %}
    <td>
    {# Include the hidden fields in the form #}
    {% if forloop.first %}
      {% for hidden in form.hidden_fields %}
      {{ hidden }}
      {% endfor %}
    {% endif %}
      {{ field.errors.as_ul }}
      {{ field }}
    </td>
  {% endfor %}
  </tr>
{% endfor %}
</table>
{% csrf_token %}
<input type="submit" value="Guardar" />
<input type="submit" value="Nuevo" />
<input type="hidden" name="next" value="{{ next }}" />

</form>

{% endblock %}

Especialista/templates/ver_ficha.html
{% extends "columna_pagina.html" %}
{% load static %}
{% block cabecera %}
{{ block.super }}
{{ ficha.media }}
{{ agresor.media }}
{% endblock %}
{% block columnaIzq %}
	{% include "partes/persona_menu.html" with object=object.Paciente %}
{% endblock %}
{% block columnaDer %}


<h1>Ficha {{ object.ficha_type | capfirst }}</h1>
{% if user.Especialidad = 1 and object.ficha_type == 'social' and object.Finalizado = False %}
<a href="{{ object.get_modificar_enlace }}">Modificar</a>
{%endif%}

{% if user.Especialidad = 3 and object.ficha_type == 'infantil' and object.Finalizado = False %}
<a href="{{ object.get_modificar_enlace }}">Modificar</a>
{%endif%}

{% if user.Especialidad = 3 and object.ficha_type == 'psicologica' and object.Finalizado = False %}
<a href="{{ object.get_modificar_enlace }}">Modificar</a>
{%endif%}

{% if user.Especialidad = 4 and object.ficha_type == 'medica' and object.Finalizado = False %}
<a href="{{ object.get_modificar_enlace }}">Modificar</a>
{%endif%}

{% if user.Especialidad = 2 and object.ficha_type == 'juridica' and object.Finalizado = False %}
<a href="{{ object.get_modificar_enlace }}">Modificar</a>
{%endif%}

<div class="data">
<table>
    <!-- Este muestra los datos de las fichas de adulto y este autovista en particular (porque hay varios) está definido en view de Especialistas -->
	{{ autovista.as_table }} 
</table>
<h4>Observaciones</h4>
<table>
	<thead>
		<tr><th>Fecha</th><th>Observación</th></tr>
	</thead>
	<tbody>
		{% for ob in object.observacion_set.all %}
			<tr>
				<td>{{ ob.fecha }}</td><td>{{ ob.texto }}</td>
			</tr>
		{% endfor %}
	</tbody>
</table>
</div>

<div align="right">
{%if object.ficha_type != 'infantil'%}
<a href="{% url 'imprimir_ficha' pk=object.Paciente_id tipo=object.ficha_type ficha_pk=object.pk %}"><img src="{% static 'img/printer.png' %}" width="32" height="32"></a>
{%else%}
<a href="{% url 'imprimir_ficha' pk=object.Paciente_id tipo='psicosocial' ficha_pk=object.pk %}"><img src="{% static 'img/printer.png' %}" width="32" height="32"></a>
{%comment%}<a href="{{ object.get_absolute_url }}">{{ ficha.FechaActualizada }}<img src="{% static 'img/printer.png' %}" width="32" height="32" align="right"></a>{%endcomment%}
{%endif%}
</div>
{% endblock %}

Especialista/templates/ver_ficha_infante.html
{% extends "columna_pagina.html" %}
{% load static %}
{% block cabecera %}
{{ block.super }}
{{ ficha.media }}
{{ agresor.media }}
{% endblock %}
{% block columnaIzq %}
	{% include "partes/persona_menu.html" with object=object.Paciente %}
{% endblock %}
{% block columnaDer %}

<h1>Ficha {{ object.ficha_type | capfirst }}</h1>
<a href="{% url 'modificar_ficha_infante' object.Paciente_id object.pk %}">Modificar</a>

<table>
	<tbody>
		{% for nombre, valor in object.sub_model.get_fields %}
		<tr><td>{{ nombre }}</td><td>{{ valor }}</td></tr>
		{% endfor %}
	</tbody>
</table>
<h1>Observaciones</h1>
<table>
	<thead>
		<tr><th>Fecha</th><th>Observación</th></tr>
	</thead>
	<tbody>
		{% for ob in object.observacion_set.all %}
			<tr>
				<td>{{ ob.fecha }}</td><td>{{ ob.texto }}</td>
			</tr>
		{% endfor %}
	</tbody>
</table>
</div>

{% endblock %}